[package]
name = "connectify"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.2", features = ["full"] }
futures-util = "0.3.31"
tokio-tungstenite = "0.26.2"
http = "1.3.1"
url = "2.5.4"

[lib]
path = "src/lib.rs"